---
- hosts: '{{ var_hosts | default("laputa.danizen.net") }}'
  become: true
  vars:
    pocketmine_dir: /home/pocketmine
    pocketmine_user: pmmp
    pocketmine_group: pmmp
    pocketmine_service_name: pocketmine
    pocketmine_console_fifo: /var/run/{{ pocketmine_service_name }}/console
    pocketmine_console_fifo_mode: '0666'

  tasks:
    - name: Add additional yum repositories on CentOS
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - epel-release
      when: "ansible_os_family == 'RedHat'"

    - name: Upgrade all packages
      yum: name=* state=latest update_cache=yes
      when: "ansible_os_family == 'RedHat'"

    - name: Create pocketmine group
      group:
        name: '{{ pocketmine_group }}'

    - name: Create pocketmine user
      user:
        name: '{{ pocketmine_user }}'
        comment: PocketMine-MP service account
        home: '{{ pocketmine_dir }}'
        group: '{{ pocketmine_group }}'

    - name: Create directory for pocketmine
      file:
        path: '{{ pocketmine_dir }}'
        state: directory

    - name: Download pre-build scripts
      get_url:
        url: http://get.pmmp.io/
        dest: '{{ pocketmine_dir }}/pmmp_installer.sh'
        owner: '{{ pocketmine_user }}'
        group: '{{ pocketmine_group }}'
        mode: 0755

    - name: Build pocketmine
      command: 'su - {{pocketmine_user}} -c "{{ pocketmine_dir }}/pmmp_installer.sh"'
      args:
        chdir: '{{ pocketmine_dir }}'
        creates: '{{ pocketmine_dir }}/PocketMine-MP.phar'

    - import_tasks: download-plugins.yml

    - import_tasks: systemd.yml
